research_task:
  description: >
    Conduct a thorough research about {topic}.
    Make sure you find any interesting and relevant information given
    the current year is {current_year}.
  expected_output: >
    A list with 10 bullet points of the most relevant information about {topic}.
  agent: researcher

outline_task:
  description: >
    Create a clear, logical, and comprehensive article outline based on the research findings about {topic}.
    Structure the article to guide a writer through a coherent and engaging narrative.
  expected_output: >
    A hierarchical outline with sections and subsections ready for content development.
  agent: outline_specialist

writing_task:
  description: >
    Write a well-informed and engaging article on {topic} based on the approved outline and research insights.
    Ensure the content is accessible, technically accurate, and aligned with the target audience.
  expected_output: >
    A complete article draft of 800–1500 words that reflects the structure of the outline and integrates the research findings.
  agent: writer

editing_task:
  description: >
    Review the article draft on {topic} to ensure clarity, consistency, grammar correctness, and overall quality.
    Optimize the tone and polish the content to meet publication standards.
  expected_output: >
    A final version of the article that is clean, professional, and ready for publishing.
  agent: editor

